Fixed some issues, and implemented the quick flag

diff --git a/src/kittyvault b/src/kittyvault
--- a/src/kittyvault
+++ b/src/kittyvault
@@ -2,13 +2,17 @@
 
 set -euo pipefail
 
+# DEBUG: Reset flags
+./scripts/gen-flags.sh
+
 # --------------------------------------------------------------------------------------------
 # kittyvault — Usb encrypter using veracrypt
 # --------------------------------------------------------------------------------------------
 
-VERSION="kittyvault version 0.1.0 (dev)"
-SELECTED_DISK=""
-DEPENDENCIES=("lolcat" "veracrypt")
+VERSION="kittyvault version 0.1.0 (dev)" # Version message
+DEPENDENCIES=("lolcat" "veracrypt")      # Required programs
+SELECTED_DISK=""                         # Target external disk to be worked with
+QUICK_MODE=""                            # Can be enabled to make creating a new KittyVault faster
 
 # User input ---------------------------------------------------------------------------------
 
@@ -17,11 +21,11 @@ get_number() {
     local valid_num=false
     while [[ "$valid_num" == false ]]; do
         read -p " > " num
-        if [[ "$num" =~ ^[0-9]+$ ]] && ((num >= 0 && num < $1)); then
+        if [[ "$num" =~ ^[0-9]+$ ]] && ((num >= $1 && num <= $2)); then
             echo "$num"
             valid_num=true
         else
-            echo "Invalid input. Please enter a number from 0 to $(($1 - 1))"
+            echo "Invalid input. Please enter a number from $1 to $2" >&2
         fi
     done
 }
@@ -54,18 +58,22 @@ ensure_set() {
 }
 
 select_disk() {
+    shopt -s extglob # for removing spaces from disk_name
     disks=($(diskutil list | grep "external" | awk '{print $1}' || true))
     if [[ ${#disks[@]} -eq 0 ]]; then
         echo "No external disks found..."
         exit 1
     fi
     echo "Select target disk:"
-    for ((i = 0; i < ${#disks[@]}; i++)); do
-        item="${disks[$i]}"
-        echo "  $i) $item ($(diskutil info "$item" | grep "Disk Size:" | awk '{print $3  $4}'))"
+    for ((i = 1; i <= ${#disks[@]}; i++)); do
+        disk_path="${disks[($i - 1)]}"
+        disk_name=$(diskutil info "$disk_path" | grep "Media Name:" | awk -F ":" '{print $2}')
+        disk_size=$(diskutil info "$disk_path" | grep "Disk Size:" | awk '{print $3  $4}')
+        echo "  $i) ${disk_name##*([[:space:]])} ($disk_path) ($disk_size)"
     done
-    index=$(get_number ${#disks[@]})
-    SELECTED_DISK=${disks[$index]}
+    index=$(get_number 1 ${#disks[@]})
+    SELECTED_DISK=${disks[($index - 1)]}
+    shopt -u extglob
 }
 
 # --------------------------------------------------------------------------------------------
@@ -75,102 +83,84 @@ select_disk() {
 parser_definition() {
     setup REST help:usage -- "Usage: kittyvault [options]... [arguments]..." ''
     msg -- 'Options:'
-    flag QUICK -q --quick -- "Skip overwriting disk with random data on creation"
+    flag QUICK_MODE -q --quick on:"--quick" -- "Skip overwriting disk with random data on creation"
     disp :usage -h --help -- "Display help message"
     disp VERSION --version
 }
 # @end
 
+# [parser code]
 # @gengetoptions parser -i parser_definition parse
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.2)
-QUICK=''
+QUICK_MODE=''
 REST=''
 parse() {
-    OPTIND=$(($# + 1))
-    while OPTARG= && [ "${REST}" != x ] && [ $# -gt 0 ]; do
-        case $1 in
-        --?*=*)
-            OPTARG=$1
-            shift
-            eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
-            ;;
-        --no-* | --without-*) unset OPTARG ;;
-        -[qh]?*)
-            OPTARG=$1
-            shift
-            eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
-            case $2 in --*) set -- "$1" unknown "$2" && REST=x ;; esac
-            OPTARG=
-            ;;
-        esac
-        case $1 in
-        '-q' | '--quick')
-            [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
-            eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG=''
-            QUICK="$OPTARG"
-            ;;
-        '-h' | '--help')
-            usage
-            exit 0
-            ;;
-        '--version')
-            echo "${VERSION}"
-            exit 0
-            ;;
-        --)
-            shift
-            while [ $# -gt 0 ]; do
-                REST="${REST} \"\${$(($OPTIND - $#))}\""
-                shift
-            done
-            break
-            ;;
-        [-]?*)
-            set "unknown" "$1"
-            break
-            ;;
-        *)
-            REST="${REST} \"\${$(($OPTIND - $#))}\""
-            ;;
-        esac
-        shift
-    done
-    [ $# -eq 0 ] && {
-        OPTIND=1
-        unset OPTARG
-        return 0
-    }
+  OPTIND=$(($#+1))
+  while OPTARG= && [ "${REST}" != x ] && [ $# -gt 0 ]; do
     case $1 in
+      --?*=*) OPTARG=$1; shift
+        eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
+        ;;
+      --no-*|--without-*) unset OPTARG ;;
+      -[qh]?*) OPTARG=$1; shift
+        eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
+        case $2 in --*) set -- "$1" unknown "$2" && REST=x; esac;OPTARG= ;;
+    esac
+    case $1 in
+      '-q'|'--quick')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='--quick' || OPTARG=''
+        QUICK_MODE="$OPTARG"
+        ;;
+      '-h'|'--help')
+        usage
+        exit 0 ;;
+      '--version')
+        echo "${VERSION}"
+        exit 0 ;;
+      --)
+        shift
+        while [ $# -gt 0 ]; do
+          REST="${REST} \"\${$(($OPTIND-$#))}\""
+          shift
+        done
+        break ;;
+      [-]?*) set "unknown" "$1"; break ;;
+      *)
+        REST="${REST} \"\${$(($OPTIND-$#))}\""
+    esac
+    shift
+  done
+  [ $# -eq 0 ] && { OPTIND=1; unset OPTARG; return 0; }
+  case $1 in
     unknown) set "Unrecognized option: $2" "$@" ;;
     noarg) set "Does not allow an argument: $2" "$@" ;;
     required) set "Requires an argument: $2" "$@" ;;
     pattern:*) set "Does not match the pattern (${1#*:}): $2" "$@" ;;
     notcmd) set "Not a command: $2" "$@" ;;
-    *) set "Validation error ($1): $2" "$@" ;;
-    esac
-    echo "$1" >&2
-    exit 1
+    *) set "Validation error ($1): $2" "$@"
+  esac
+  echo "$1" >&2
+  exit 1
 }
 usage() {
-    cat <<'GETOPTIONSHERE'
+cat<<'GETOPTIONSHERE'
 Usage: kittyvault [options]... [arguments]...
 
 Options:
   -q, --quick                 Skip overwriting disk with random data on creation
   -h, --help                  Display help message
-      --version
+      --version               
 GETOPTIONSHERE
 }
 # Generated by getoptions (END)
 # @end
+# [/]
 
 parse "$@"
 eval "set -- $REST"
 printf '%s\n' "$@"
-
-echo "$QUICK" # DEBUG
-exit 0        # DEBUG
 
 # Dependencies -------------------------------------------------------------------------------
 
@@ -208,6 +198,6 @@ veracrypt --text --create \
     --hash SHA-512 \
     --filesystem exFAT \
     --password "$password" \
-    --quick \
+    $QUICK_MODE \
     --non-interactive
 echo "--- Veracrypt --- "
